### ISSUE TITLE
testsuite failing in Stackage build

### ISSUE THREAD

**Issue by juhp** [emmanueltouzery/app-settings#6] opened 2015-10-06 09:42 UTC
app-settings-0.2.0.6 tests failing in the Stackage nightly build:

```
Test suite tests: RUNNING...

unit tests
  checks correctly whether a key is attached to a list setting
load config
  parses correctly an empty file with defaults
  parses correctly a partial file with defaults FAILED [1]
  parses correctly a partial2 file with defaults FAILED [2]
  parses correctly a partial file with comments FAILED [3]
  reports errors properly for invalid files FAILED [4]
  parses correctly a file with invalid values FAILED [5]
  returns empty config for a non-existing file
  Reads setting files with setting values wrapped over several lines FAILED [6]
save config
  saves a file with user-set and default settings FAILED [7]
  creates a backup of the config file before overwriting it FAILED [8]
  wraps long settings when saving FAILED [9]
set setting
  overwrites correctly a list setting

Failures:

  tests/Tests.hs:66:
  1) load config parses correctly a partial file with defaults
       expected: 1.02
        but got: 4.0e-2

  tests/Tests.hs:78:
  2) load config parses correctly a partial2 file with defaults
       expected: 1.02
        but got: 4.0e-2

  tests/Tests.hs:90:
  3) load config parses correctly a partial file with comments
       expected: 1.02
        but got: 4.0e-2

  tests/Tests.hs:137:
  4) load config reports errors properly for invalid files
       did not get an error!

  tests/Tests.hs:102:
  5) load config parses correctly a file with invalid values
       expected: (1.0,2.0,3.0,4.0)
        but got: (1.0,1.0,0.0,1.0)

  tests/Tests.hs:127:
  6) load config Reads setting files with setting values wrapped over several lines
       doesn't match
       expected: ["long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string","long      string"]
        but got: ["inline1","inline2","inline3"]

  tests/Tests.hs:144:
  7) save config saves a file with user-set and default settings
       uncaught exception: IOException of type NoSuchThing (tests/test-save.txt: openFile: does not exist (No such file or directory))

  tests/Tests.hs:156:
  8) save config creates a backup of the config file before overwriting it
       uncaught exception: IOException of type NoSuchThing (tests/partial.config: copyFile: does not exist (No such file or directory))

  tests/Tests.hs:169:
  9) save config wraps long settings when saving
       uncaught exception: IOException of type NoSuchThing (tests/longsetting.conf: openFile: does not exist (No such file or directory))

Randomized with seed 862420682

Finished in 0.0024 seconds
13 examples, 9 failures
Test suite tests: FAIL
```

**Comment by emmanueltouzery** [comment] 2015-10-06 10:02
I think it's simply that I forgot to tell cabal to ship the test files in the package. Uploaded a new version on hackage now. Closing, please reopen if the problem is not fixed, and thanks for the heads up!!

**Closed by emmanueltouzery** 2015-10-06 10:02 UTC

**Comment by juhp** [comment] 2015-10-06 11:10
Thanks that did it!
